util.AddNetworkString("TKGOsaka_MusicPanel")
util.AddNetworkString("TKGOsaka_MusicL")
util.AddNetworkString("TKGOsaka_MusicS")
concommand.Add("oui", function( ply, cmd, args )
	net.Start("TKGOsaka_MusicPanel")
	net.Send(ply)
end)

concommand.Add("oui2", function( ply, cmd, args )
	net.Start("TKGOsaka_MusicL")
	net.Send(ply)
end)
concommand.Add("oui3", function( ply, cmd, args )
	net.Start("TKGOsaka_MusicS")
	net.Send(ply)
end)